# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Wake & Act' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ChameleonFramework', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'SwiftyUserDefaults'

end
