platform :ios, '9.0'
use_frameworks!

target 'Wake & Act' do

	# Persistance
	pod 'AlecrimCoreData', '~> 5.0'
  pod 'SwiftyUserDefaults'
	
	# UI
	pod 'ChameleonFramework', :git => 'https://github.com/ViccAlexander/Chameleon.git'
	pod 'Macaw'
	pod 'DZNEmptyDataSet'
	
	# Reactive programming
	pod 'RxSwift', '~> 3.0'
	pod 'RxCocoa', '~> 3.0'
	pod 'Moya/RxSwift'
	pod 'NSObject+Rx'
	
	# Internet
	pod 'SwiftyJSON'
	pod 'Alamofire'
	pod 'SDWebImage', '~> 3.7'
	pod 'ReachabilitySwift'

end

target 'Wake & Act Tests' do

	pod 'RxBlocking', '~> 3.0'
	pod 'RxTest', '~> 3.0'
	pod 'Quick'
	pod 'Nimble'
	pod 'Forgeries'
	pod 'Nimble-Snapshots'

end
